name: sakai_mobile
description: Sakai Mobile is an unofficial mobile client for Sakai LMS
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  intl: ^0.18.0
  flutter_launcher_icons: ^0.13.1

  page_transition: ^2.0.9
  flutter_screenutil: ^5.7.0
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.10

  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  flutter_inappwebview: ^6.0.0
  html: ^0.15.4

  outline_gradient_button: ^2.0.1+1
  auto_size_text: ^3.0.0
  flutter_snake_navigationbar: ^0.6.1
  flutter_slider_drawer: ^2.1.3
  animated_tree_view: ^2.2.0
  flutter_html: ^3.0.0-beta.2

  path_provider: ^2.1.2
  share_plus: ^7.2.2
  http: ^1.2.1
  mime_type: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/images/
  fonts:
    - family: NotoSans
      fonts: 
        - asset: assets/fonts/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansJP-VariableFont_wght.ttf

flutter_icons:       
  android: true
  ios: true
  image_path: "assets/images/icon.png"